const actionTypes = {
	bookActions:{
		GET_BOOKS_START:"GET_BOOKS_START",
		GET_BOOKS_SUCCESS:"GET_BOOKS_SUCCESS",
		GET_BOOKS_FAIL:"GET_BOOKS_FAIL",
		ADD_BOOK:"ADD_BOOK",
		DELETE_BOOK:"DELETE_BOOK",
		EDİT_BOOK:"EDİT_BOOK"
	},
	categoryActions:{
		GET_CATEGORİES_START:"GET_CATEGORİES_START",
		GET_CATEGORİES_SUCCESS:"GET_CATEGORİES_SUCCESS",
		GET_CATEGORİES_FAIL:"GET_CATEGORİES_FAIL",
		ADD_CATEGORY:"ADD_CATEGORY",
		DELETE_CATEGORY:"DELETE_CATEGORY"
	},
	themeActions:{
		CHANGE_THEME:"CHANGE_THEME"
	}
}

export default actionTypes;